services:
  - type: web
    name: streamer-tma-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: STREAMER_NAME
        value: StreamerLegend
      - key: DEBUG_MODE
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: API_PORT
        value: 10000
